#!/usr/bin/env bash
# ============================================================
#  setup_wireguard.sh — Generate WireGuard keys and build
#  client config for the ESP32-S3 NAT Router
#
#  Usage:
#    chmod +x setup_wireguard.sh
#    ./setup_wireguard.sh
# ============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${CYAN}[INFO]${NC}  $1"; }
log_ok()   { echo -e "${GREEN}[OK]${NC}    $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_err()  { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Check wg tool
command -v wg &> /dev/null || log_err "WireGuard tools not installed.\n  Install: apt install wireguard-tools (Linux) or brew install wireguard-tools (macOS)"

KEYS_DIR="./vpn/keys"
mkdir -p "$KEYS_DIR"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   WireGuard Key Generator                ║${NC}"
echo -e "${CYAN}║   ESP32-S3 NAT Router Setup              ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Generate ESP32 Key Pair ───────────────────────────────────
log_info "Generating ESP32-S3 WireGuard key pair..."
ESP32_PRIVKEY=$(wg genkey)
ESP32_PUBKEY=$(echo "$ESP32_PRIVKEY" | wg pubkey)

echo "$ESP32_PRIVKEY" > "${KEYS_DIR}/esp32_private.key"
echo "$ESP32_PUBKEY"  > "${KEYS_DIR}/esp32_public.key"
chmod 600 "${KEYS_DIR}/esp32_private.key"
log_ok "ESP32 keys generated."

# ── Generate Peer #1 Key Pair ─────────────────────────────────
log_info "Generating Peer #1 (client device) key pair..."
PEER1_PRIVKEY=$(wg genkey)
PEER1_PUBKEY=$(echo "$PEER1_PRIVKEY" | wg pubkey)
PRESHARED_KEY=$(wg genpsk)

echo "$PEER1_PRIVKEY" > "${KEYS_DIR}/peer1_private.key"
echo "$PEER1_PUBKEY"  > "${KEYS_DIR}/peer1_public.key"
echo "$PRESHARED_KEY" > "${KEYS_DIR}/preshared.key"
chmod 600 "${KEYS_DIR}/peer1_private.key" "${KEYS_DIR}/preshared.key"
log_ok "Peer #1 keys generated."

# ── Write ESP32 wg0.conf ──────────────────────────────────────
log_info "Writing ESP32 WireGuard config..."
cat > ./vpn/wg0.conf << EOF
# ============================================================
#  WireGuard Config — ESP32-S3 Interface (wg0)
#  AUTO-GENERATED by setup_wireguard.sh
#  Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ============================================================

[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = ${ESP32_PRIVKEY}
DNS = 1.1.1.1, 8.8.8.8
MTU = 1380

[Peer]
# Peer: Client Device
PublicKey = ${PEER1_PUBKEY}
PresharedKey = ${PRESHARED_KEY}
AllowedIPs = 10.0.0.2/32
PersistentKeepalive = 25
EOF
log_ok "ESP32 config written to vpn/wg0.conf"

# ── Write Client Config ───────────────────────────────────────
log_info "Writing client WireGuard config..."
cat > ./vpn/client_peer1.conf << EOF
# ============================================================
#  WireGuard Config — Client Device (Peer #1)
#  AUTO-GENERATED by setup_wireguard.sh
# ============================================================
#  Import this file into your WireGuard app:
#    - Android/iOS: Scan QR code (use: qrencode -t ansiutf8 < client_peer1.conf)
#    - Windows/Linux: Import .conf file
# ============================================================

[Interface]
Address = 10.0.0.2/32
PrivateKey = ${PEER1_PRIVKEY}
DNS = 1.1.1.1, 8.8.8.8

[Peer]
# ESP32-S3 NAT Router
PublicKey = ${ESP32_PUBKEY}
PresharedKey = ${PRESHARED_KEY}
AllowedIPs = 10.0.0.0/24
Endpoint = <ESP32_WAN_IP>:51820
PersistentKeepalive = 25
EOF
log_ok "Client config written to vpn/client_peer1.conf"

# ── Summary ────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Key Generation Complete!                    ${NC}"
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${CYAN}ESP32 Public Key:${NC}  ${ESP32_PUBKEY}"
echo -e "  ${CYAN}Peer #1 Pub Key:${NC}   ${PEER1_PUBKEY}"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "  1. Flash wg0.conf to ESP32 via web UI at http://192.168.4.1"
echo -e "  2. Import client_peer1.conf into your WireGuard app"
echo -e "  3. Replace <ESP32_WAN_IP> in client_peer1.conf with your ESP32's actual IP"
echo -e "  4. Connect and verify: ping 10.0.0.1"
echo ""
log_warn "Keep keys in vpn/keys/ secure. Do NOT commit them to public repos!"
